$ErrorActionPreference = "Stop"

$tid = "<TENANT_ID>"
$ws  = "<WORKSPACE_ID>"
$ont = "<ONTOLOGY_ID_V1>"

$T  = "`t"
$NL = "`r`n"

function NewGuid { [guid]::NewGuid().ToString() }

$entityDocs = @{
  "Customer"     = "A NovaTel enterprise account. The commercial subject the whole ontology hangs from."
  "Product"      = "A commercial offer NovaTel sells, with its category and margin profile."
  "Subscription" = "The commercial relationship linking a customer to a product, carrying seats and ARR."
  "Usage"        = "Monthly consumption and network-quality signals generated by a subscription."
  "Experience"   = "Support tickets, severity, and SLA breaches describing how well the customer is served."
  "RenewalRisk"  = "Renewal timing, negotiation stage, and NPS that express commercial risk."
}

# from -> verb -> to
$relationships = @(
  @{ Name = "owns";         From = "Customer";     To = "Subscription"; Doc = "A customer owns one or more subscriptions." },
  @{ Name = "contains";     From = "Subscription"; To = "Product";      Doc = "A subscription contains the product being sold." },
  @{ Name = "generates";    From = "Subscription"; To = "Usage";        Doc = "A subscription generates monthly consumption." },
  @{ Name = "affects";      From = "Usage";        To = "Experience";   Doc = "Consumption growth and network quality affect the support experience." },
  @{ Name = "increases";    From = "Experience";   To = "RenewalRisk";  Doc = "A degraded experience increases renewal risk." },
  @{ Name = "reports";      From = "Customer";     To = "Experience";   Doc = "A customer reports support tickets." },
  @{ Name = "faces";        From = "Customer";     To = "RenewalRisk";  Doc = "A customer faces a renewal decision with measurable risk." }
)

$fabricToken = az account get-access-token --tenant $tid --resource https://api.fabric.microsoft.com --query accessToken -o tsv
$fh = @{ Authorization = "Bearer $fabricToken"; "Content-Type" = "application/json" }

$current = Invoke-RestMethod "https://api.fabric.microsoft.com/v1/workspaces/$ws/ontologies/$ont/getDefinition" `
  -Method Post -Headers $fh -TimeoutSec 180

$parts = @{}
foreach ($p in $current.definition.parts) {
  $parts[$p.path] = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($p.payload))
}

$entityNames = @("Customer", "Product", "Subscription", "Usage", "Experience", "RenewalRisk")

# ---- entities/*.tmdl (semantic layer over the backing tables) ----
foreach ($name in $entityNames) {
  $path = "entities/$name.tmdl"
  $lineage = NewGuid
  if ($parts.ContainsKey($path) -and $parts[$path] -match "lineageTag:\s*([0-9a-fA-F-]{36})") {
    $lineage = $Matches[1]   # preserve existing identity
  }
  $doc = $entityDocs[$name]
  $tmdl  = "/// $doc$NL"
  $tmdl += "entity $name$NL"
  $tmdl += "${T}lineageTag: $lineage$NL"
  $tmdl += "${T}backingTable: $name$NL"
  $parts[$path] = $tmdl
  Write-Host "entity: $name"
}

# ---- entityRelationships.tmdl ----
$existingLineage = @{}
if ($parts.ContainsKey("entityRelationships.tmdl")) {
  $blocks = $parts["entityRelationships.tmdl"] -split "entityRelationship "
  foreach ($b in $blocks) {
    if ($b -match "^(\w+)" ) {
      $rn = $Matches[1]
      if ($b -match "lineageTag:\s*([0-9a-fA-F-]{36})") { $existingLineage[$rn] = $Matches[1] }
    }
  }
}

$rel = ""
foreach ($r in $relationships) {
  $lineage = if ($existingLineage.ContainsKey($r.Name)) { $existingLineage[$r.Name] } else { NewGuid }
  $rel += "/// $($r.Doc)$NL"
  $rel += "entityRelationship $($r.Name)$NL"
  $rel += "${T}label: $($r.Name)$NL"
  $rel += "${T}lineageTag: $lineage$NL"
  $rel += "${T}fromEntity: $($r.From)$NL"
  $rel += "${T}toEntity: $($r.To)$NL$NL"
  Write-Host "relationship: $($r.From) -$($r.Name)-> $($r.To)"
}
$parts["entityRelationships.tmdl"] = $rel

# ---- model.tmdl ----
$model = "model Model$NL$NL"
foreach ($n in $entityNames) { $model += "ref table $n$NL" }
$model += $NL
foreach ($n in $entityNames) { $model += "ref entity $n$NL" }
$model += $NL + "ref namespace default$NL$NL"
$parts["model.tmdl"] = $model

# ---- submit ----
$payloadParts = @()
foreach ($path in $parts.Keys) {
  $payloadParts += @{
    path        = $path
    payload     = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($parts[$path]))
    payloadType = "InlineBase64"
  }
}

$body = @{ definition = @{ parts = $payloadParts } } | ConvertTo-Json -Depth 8
$body | Set-Content "body-full.json" -Encoding utf8

Write-Host ""
Write-Host "Enviando $($payloadParts.Count) partes..."

try {
  $r = Invoke-WebRequest "https://api.fabric.microsoft.com/v1/workspaces/$ws/ontologies/$ont/updateDefinition?updateMetadata=true" `
    -Method Post -Headers $fh -Body $body -TimeoutSec 300
  Write-Host "SUCESSO status=$($r.StatusCode)" -ForegroundColor Green
}
catch {
  $m = $_.ErrorDetails.Message
  if (-not $m) { $m = $_.Exception.Message }
  Write-Host "FALHA:" -ForegroundColor Yellow
  Write-Host $m
}
